---
name: Go Release on Tag
on:
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
      - name: Get version from tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build Go Application
        run: >
          echo "Building version $VERSION..." #use shell variable here.

          go build -v -ldflags="-s -w -X 'main.version=${{ github.ref_name }}'" -o git-reports .
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            git-reports

